apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurio
spec:
  configuration:
    kafkasql:
      bootstrapServers: 'fights-kafka-kakfa-bootstrap:9092'
    persistence: kafkasql