apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: superhero-battle-cicd

bases:
  - ../../../base/cicd/quarkus-pipeline

patches:
  - target:
      group: ''
      version: v1
      kind: PersistentVolumeClaim
      name: quarkus-workspace
    patch: |-
      - op: replace
        path: /metadata/name
        value: rest-fights-workspace
  - target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      name: quarkus-pipeline
    patch: |-
      - op: replace
        path: /metadata/name
        value: rest-fights-pipeline
