kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-gitops

bases:
  - ../../../cluster-services/openshift-pipelines
  - ../../../cluster-services/web-terminal
#  - ../../../03-cluster-services/06-workload-monitoring
#  - ../../../03-cluster-services/07-compliance

resources:
  - cluster-services-project.yaml
