apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rest-heroes
    application: heroes-service
    system: quarkus-super-heroes
  name: rest-heroes-config
data:
  quarkus.hibernate-orm.database.generation: validate
  quarkus.hibernate-orm.sql-load-script: no-file
  quarkus.datasource.jdbc.url: jdbc:postgresql://heroes-db:5432/heroes_database
  #quarkus.datasource.jdbc.url: jdbc:otel:postgresql://heroes-db:5432/heroes_database
  quarkus.opentelemetry.tracer.exporter.otlp.endpoint: http://otel-collector:4317