apiVersion: batch/v1
kind: Job
metadata:
  name: compile-compliance-report
spec:
  template:
    metadata:
      name: compile-compliance-report
    spec:
      containers:
        - name: oc-compliance
          image: quay.io/pittar/oc-compliance:latest
          volumeMounts:
            - name: report-volume
              mountPath: /reports
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              oc compliance fetch-raw scansettingbindings ocp4-moderate-compliance -n openshift-compliance -o /reports
              oc compliance fetch-raw scansettingbindings rhcos4-moderate-compliance -n openshift-compliance -o /reports
              build-reports.sh /reports
      restartPolicy: Never
      volumes:
      - name: report-volume
        persistentVolumeClaim:
          claimName: report-volume