apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2022-08-24T15:53:02Z'
  generation: 17
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2022-08-24T16:01:17Z'
  name: compliance-report-builder
  namespace: compliance
  resourceVersion: '924535'
  uid: e4ae7a60-a55c-4645-96a8-999413c88f2a
spec:
  params:
    - description: Name of scans to include.
      name: scan-names
      type: string
  steps:
    - image: 'quay.io/pittar/oc-compliance:latest'
      name: compliance-toolbox
      resources: {}
      script: |
        #!/usr/bin/env bash
        set +x
        export NO_COLOR="True"
        rm -rf $(workspaces.reports.path)/ocp4*
        rm -rf $(workspaces.reports.path)/rhcos4*

        oc compliance \
          fetch-raw \
          scansettingbindings \
          ocp4-moderate-compliance \
          -n openshift-compliance -o $(workspaces.reports.path)

        oc compliance \
          fetch-raw \
          scansettingbindings \
          rhcos4-moderate-compliance \
          -n openshift-compliance -o $(workspaces.reports.path)

        build-reports.sh $(workspaces.reports.path)

        ls -la

        cat > index.html << EOF
        <html>
        <head>
          <title>Compliance View</title>
        </head>
        <body>
        <h1>Compliance Results</h1>
        <div>
          <ul>
        EOF

        count=0
        for filename in html/*.html; do
            ((count=count + 1))
            if [ -f "$filename" ]; then
                echo "Filename: $filename"
                htmlfilename=$(echo $filename | sed 's/\///g' | sed "s/html//")
                echo "Generating $htmlfilename"
                echo "<li><a href='"$htmlfilename"'>$htmlfilename</a></li>" >> index.html
            fi
        done

        cat >> index.html << EOF
          </ul>
        </div>
        </body>
        </html>
        EOF
      workingDir: $(workspaces.reports.path)
  workspaces:
    - name: reports
