apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: gitea
spec:
  giteaUserNumber: 1
  giteaGenerateUserFormat: "developer"
  giteaMigrateRepositories: true
  giteaVolumeSize: 4Gi
  giteaAdminUser: gitea-admin
  giteaImageTag: "1.15.10"
  postgresqlVolumeSize: 4Gi
  giteaUserPassword: openshift
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaAdminPassword: openshift
  giteaCreateUsers: true
  giteaSsl: true
  giteaRepositoriesList:
    - name: battle-rest-heroes
      private: false
      repo: 'https://github.com/pittar-demos/battle-rest-heroes.git'
    - name: battle-rest-villains
      private: false
      repo: 'https://github.com/pittar-demos/battle-rest-villains.git'
    - name: battle-rest-fights
      private: false
      repo: 'https://github.com/pittar-demos/battle-rest-fights.git'
    - name: battle-event-statistics
      private: false
      repo: 'https://github.com/pittar-demos/battle-event-statistics.git'
    - name: battle-ui
      private: false
      repo: 'https://github.com/pittar-demos/battle-ui.git'