apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rest-fights
    application: fights-service
    system: quarkus-super-heroes
  name: rest-fights-config
data:
  quarkus.hibernate-orm.database.generation: validate
  quarkus.hibernate-orm.sql-load-script: no-file
  quarkus.datasource.jdbc.url: jdbc:otel:postgresql://fights-db:5432/fights_database
  quarkus.opentelemetry.tracer.exporter.otlp.endpoint: http://otel-collector:4317