
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-tools

# Deploy pre-configured SonarQube and Nexus from Red Hat Canada demo catalog.
bases:
  - github.com/redhat-cop/gitops-catalog/nexus2/base?ref=main
  - github.com/redhat-cop/gitops-catalog/sonarqube8/overlays/plugins?ref=main

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: nexus
    patch: |-
      - op: add
        path: /spec/tls
        value:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: sonarqube
    patch: |-
      - op: add
        path: /spec/tls
        value:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect