kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../../03-cluster-services/openshift-pipelines
  - ../../../03-cluster-services/web-terminal-operator
  - ../../../03-cluster-services/strimzi-operator
  - ../../../03-cluster-services/openshift-devspaces
  - ../../../03-cluster-services/gitea/operator
  - ../../../03-cluster-services/gitea/instance
  - ../../../03-cluster-services/common-cicd-tools
#  - ../../../03-cluster-services/07-compliance

resources:
  - cluster-services-project.yaml
