apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: superhero-battle-cicd

resources:
  - battle-ui-pipeline.yaml
  - battle-ui-workspace-pvc.yaml
  - event-statistics-pipeline.yaml
  - event-statistics-workspace-pvc.yaml
  - rest-fights-pipeline.yaml
  - rest-fights-workspace-pvc.yaml
  - rest-heroes-pipeline.yaml
  - rest-heroes-workspace-pvc.yaml
  - rest-villains-pipeline.yaml
  - rest-villains-workspace-pvc.yaml
