apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: superhero-battle-cicd

bases:
  - battle-ui-pipeline
  - event-statistics-pipeline
  - rest-fights-pipeline
  - rest-heroes-pipeline
  - rest-villains-pipeline
  - triggers

resources:
  # - battle-ui-pipeline.yaml
  # - battle-ui-workspace-pvc.yaml
  # - event-statistics-pipeline.yaml
  # - event-statistics-workspace-pvc.yaml
  # - rest-fights-pipeline.yaml
  # - rest-fights-workspace-pvc.yaml
  # - rest-heroes-pipeline.yaml
  # - rest-heroes-workspace-pvc.yaml
  # - rest-villains-pipeline.yaml
  # - rest-villains-workspace-pvc.yaml
  - image-puller-rbac.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: superhero-battle-cicd-image-puller
    path: image-puller-rbac-patch.yaml